[id="constants"]

= Cairo 合约中的常量

在本章中，我们将讨论在 Cairo 合约中使用常量。常量对于定义在合约执行过程中不会改变的值非常有用。我们将继续使用修改后的 Vote 合约。

== 定义常量

要在 Cairo 合约中定义常量，您需要使用 const 关键字，后面跟着常量的名称、类型和值。常量可以是任何 Cairo 支持的数据类型，如 u8、u16 、u256 等。

在 Vote 合约中，我们定义两个常量来表示投票选项。这有助于我们通过为值 0 和 1 提供有意义的名称来提高合约代码的可读性：

[source,cairo]
----
const YES: u8 = 1_u8;
const NO: u8 = 0_u8;
----

这里，我们定义了两个类型为 `u8` 的常量 `YES` 和 `NO`，它们的值分别为 1 和 0。

== 使用常量

常量可以像合约中的任何其他变量一样使用。主要区别在于它们的值在合约执行过程中不能更改。

在我们的 Vote 合约中，常量 `YES` 和 `NO` 用于 vote 函数以验证提交的投票并相应地更新票数。投票者调用 `vote` 函数来提交他们的投票。该函数检查提交的投票是否有效（要么是 `YES`，要么是 `NO`），并相应地更新投票数：

[source,cairo]
----
#[external]
fn vote(vote: u8) {
    // 检查投票是否有效（0 或 1）
    assert(vote == NO | vote == YES, 'VOTE_0_OR_1');

    // ... (函数的其余部分)
}
----

通过使用常量，我们提高了合约代码的可读性和可维护性。如果我们需要更改投票选项的值，我们只需要修改常量的定义。

== 使用常量的优点

在你的 Cairo 合约中使用常量有几个优点

1. 可读性：常量通过为值提供有意义的名称使代码更易读。
2. 可维护性：通过在一个地方定义值，你可以轻松地更改它们，而无需在整个代码中搜索和替换值。
3. 性能：常量可以提高性能，因为它们在编译时已知，且在运行时不占用存储或内存。

[附注]
====
《Starknet 之书》是 Starknet 社区成员合力之作，便于社区成员学习之用。

* 无论你是否有所收获，烦请填写此问卷， https://a.sprig.com/WTRtdlh2VUlja09lfnNpZDo4MTQyYTlmMy03NzdkLTQ0NDEtOTBiZC01ZjAyNDU0ZDgxMzU=[简单回答三个问题] ，给予我们反馈。
* 若发现任何错误，或有其他建议，请在我们的 https://github.com/starknet-edu/starknetbook/issues[Github 仓库]发起问题单 (Issues)。
====



== 贡献力量

[quote, Starknet 社区]

____

释放你的热情，让《Starknet 之书》更加完美

《Starknet 之书》依然在不断完善中，而你的热情、专业知识和独到见解可以将它塑造成一部真正卓越的作品。不要害怕挑战现状或是颠覆这本书！齐心协力，我们一起创造这份宝贵的资源，造福无数人。

为公共事业贡献力量。如果你发现本书有改进的空间，那就抓住机会吧！查看我们的https://github.com/starknet-edu/starknetbook/blob/main/CONTRIBUTING.adoc[指南]并加入活力满满的社区。一起无畏共建 Starknet！

____