= 第 8 章：Starknet 架构

当你开启构建可扩展的 web3 应用程序的旅程时，了解 Starknet 的架构及其它的各种组件是至关重要的。Starknet 作为第一个基于 ZK 的 rollup，自成立以来经历了巨大的发展，这要归功于其社区的卓越贡献。本章旨在深入了解 Starknet 的关键构建区块，这将使你们能够有效地开发和部署分散的应用程序（dApps）。

本章，我们将涵盖以下主题：

* L2 节点：对不同 Starknet 节点（排序器、证明者、全节点 和索引器）及其在网络中的的作用进行高级概述。
* Tx 生命周期：详细解释 L2 交易经历的各种状态，讨论将特定状态视为“最终性”的好处和风险。
* Starknet OS：探索排序器如何验证和执行交易，以及它与账户抽象 (AA) 的联系。
* SHARP：检查证明者使用递归为 Starknet 和 Starkex 生成证明的工作流程，重点关注工作流程而不是 STARK 背后的数学。
* 数据可用性：讨论 Starknet 在 Rollup 模式下的数据可用性（目前不包括 Volition）。
* L1 组件：对链上验证器和事实注册表的全面分析，以及关于 L1 逃生舱如何工作的讨论。
* 桥：解释 L1-L2 通信是如何工作的，以及如何用它来创建网络之间的桥。

到本章结束时，你将对 Starknet 生态系统的架构和组件有一个深刻的理解，使你们能够在平台上构建和部署 dApp 时做出明智的决策。


== Contributing

[quote, The Starknet Community]
____
*Unleash Your Passion to Perfect StarknetBook*

StarknetBook is a work in progress, and your passion, expertise, and unique insights can help transform it into something truly exceptional. Don't be afraid to challenge the status quo or break the Book! Together, we can create an invaluable resource that empowers countless others.

Embrace the excitement of contributing to something bigger than ourselves. If you see room for improvement, seize the opportunity! Check out our https://github.com/starknet-edu/starknetbook/blob/main/CONTRIBUTING.adoc[guidelines] and join our vibrant community. Let's fearlessly build Starknet! 
____
