[id="aa_what"]

= 什么是账户抽象？

== 账户抽象 - 定义

让我们探索一些常见的账户抽象定义：

____
定义1：账户抽象（AA）是指 *智能合约可以为自己的交易付费* (Martin Triay, Devcon 6)[1]。换句话说，抽象合约（或账户合约）可以支付交易费用。请注意，这与外部拥有账户或智能钱包不同。
____

____
定义2：账户抽象（AA）是 *验证抽象*。在L1中，验证交易的方法只有一种（从签名中检索地址，在状态中查看该地址，确定发送的交易是否符合nonce，以及账户是否有足够的余额来执行交易）。通过 AA，您可以 *抽象验证过程*：使用不同类型的签名，加密原语，执行过程等（lightclient，Devcon 6）。
____

_*注：在计算中，抽象的术语用于对某些事物进行概括。在这种情况下，我们正在这样智能合约进行概括：从现有的外部账户（EOA）和合约账户（CA）来简单概括智能合约。_

== 账户抽象的应用

AA 目标在于使自我保管账户可以更加易于实现并且通过以下措施（一个或者多个）来提高安全性：

1. 硬件签名者： 使用您的生物特征身份，在您的智能手机安全隔离区的支持下生成和保护密钥，签署交易和消息。（Starkware）[4]，（Braavos）[7]。
2. 社交恢复：在账户丢失或被盗的情况下，安全地替换控制账户的密钥，消除了种子短语的需要（Julien Niset，2022）[5]。
3. 密钥轮换：如果密钥被泄露，可以更改控制账户的密钥，而不是转移所有资产。
4. 会话密钥：登录一次，允许网站代表您执行操作，而无需不断批准交易。这为 web3 应用程序带来了更熟悉的 web2 体验。
5. 自定义交易验证方案：选择不同的签名方案、多重签名和其他安全规则（Martin Triay，Devcon 6）[1]，（Julien Niset，2022）[5]，（Motty Lavie）[7]。

AA还通过提供以下内容增强了安全性：

1. 更好的密钥管理：将设备添加到您的钱包中，即使您丢失一个设备，也可以访问。这种密钥管理的改进增强了安全性（Yoav，Devcon 6）[6]，（Motty Lavie）[7]。
2. 不同的签名和验证方案：为大额交易实施额外的安全措施，如双因素身份验证。这通过适应每个用户的特定需求实现更好的安全性（Yoav，Devcon 6）[6]，（Motty Lavie）[8]。
3. 定制安全策略：为不同类型的用户或设备量身定制安全方案，并从银行和 web2 行业中采用良好的实践（Yoav，Devcon 6）[6]。

总之，AA为以太坊生态系统中的开发人员和用户解锁了新的可能性，承诺提供更安全和用户友好的体验。通过实现各种验证方案和改进的密钥管理，AA带来了更广泛的采用的可能性和更好的用户体验。

== 参考资料：

* [1] Martin Triay, Devcon 6: https://www.youtube.com/watch?v=Osc_gwNW3Fw
* [2] Julien Niset: https://www.youtube.com/watch?v=OwppworJGzs
* [3] lightclient, Devcon 6: https://app.devcon.org/schedule/9mvqce
* [4] Starkware: https://medium.com/@starkware/how-starknet-is-revolutionizing-crypto-signing-ba3724077a79
* [5] Julien Niset, 2022: https://www.argent.xyz/blog/part-2-wtf-is-account-abstraction/
* [7] Motty Lavie, 2022: https://braavos.app/hardware-signer-innovative-security-feature-for-crypto-wallets/
* [8] Motty Lavie, 2023: https://braavos.app/account-abstraction-security-pyramid/

[NOTE]
====
这本书是社区贡献出的成果，为社区而创建。

* 如果您学到了一些东西，或者没有收获，也请花点时间通过这个 https://a.sprig.com/WTRtdlh2VUlja09lfnNpZDo4MTQyYTlmMy03NzdkLTQ0NDEtOTBiZC01ZjAyNDU0ZDgxMzU=[三个问题的调查]提供反馈。
* 如果您发现任何错误或有其他建议，请毫不犹豫地在我们的 https://github.com/starknet-edu/starknetbook/issues[GitHub 存储库上开一个 issue]。
====
