= 一个简单的 “Hello World” 账户合约

在本章中，我们将使用一个示例“Hello World”账户合约，使用Cairo语言探索Starknet中账户合约的基础知识。您可以在本章的书籍存储库的contracts目录中找到它（TODO：添加链接）。

[,Rust]
----
// 导入重要模块
#[account_contract]
mod HelloAccount {
    use starknet::ContractAddress;
    use core::felt252;
    use array::ArrayTrait;
    use array::SpanTrait;

    // 验证合约是否部署
    // 返回 starknet::VALIDATED 用来确认验证是否成功
    #[external]
    fn __validate_deploy__(
        class_hash: felt252, contract_address_salt: felt252, public_key_: felt252
    ) -> felt252 {
        starknet::VALIDATED
    }

    // 使用这个账户验证交易的声明
    // 这个函数强制要求现在需要账户支付交易费用
    // 如果验证成功，将会返回 starknet::VALIDATED
    #[external]
    fn __validate_declare__(class_hash: felt252) -> felt252 {
        starknet::VALIDATED
    }

    // 在执行交易前进行验证交易
    // 当账户合约接收到一笔交易时，该函数将被账户合约调用
    // 如果验证成功，将会返回 starknet::VALIDATED
    #[external]
    fn __validate__(
        contract_address: ContractAddress, entry_point_selector: felt252, calldata: Array::<felt252>
    ) -> felt252 {
        starknet::VALIDATED
    }

    // 执行交易
    // 如果 __validate__ 函数验证成功，此函数将会被调用
    // 此函数使用 starknet::call_contract_syscall 来调用目标合约
    #[external]
    #[raw_output]
    fn __execute__(
        contract_address: ContractAddress, entry_point_selector: felt252, calldata: Array::<felt252>
    ) -> Span::<felt252> {
        starknet::call_contract_syscall(
            address: contract_address,
            entry_point_selector: entry_point_selector,
            calldata: calldata.span()
        ).unwrap_syscall()
    }
}
----

== 外部函数

账户合约包含几个外部函数来处理交易的验证和执行。这些函数包括：

1. `__validate_deploy__`：验证合约的部署。
2. `__validate_declare__`：验证使用账户进行交易的声明。
3. `__validate__`：在执行之前验证交易。
4. `__execute__`：在成功验证后执行交易。

=== __validate_deploy__

这个函数负责验证账户合约的部署。它返回 `starknet::VALIDATED` 以确认成功验证。

[source,cairo]
----
#[external]
fn __validate_deploy__(
    class_hash: felt252, contract_address_salt: felt252, public_key_: felt252
) -> felt252 {
    starknet::VALIDATED
}
----

=== __validate_declare__

这个函数强制要求现在需要账户支付交易费用。它返回 `starknet::VALIDATED` 以确认成功验证。

[source,cairo]
----
#[external]
fn __validate_declare__(class_hash: felt252) -> felt252 {
    starknet::VALIDATED
}
----

=== __validate__

这个函数在账户合约收到交易时被调用。如果验证成功，它将返回 `starknet::VALIDATED`.

[source,cairo]
----
#[external]
fn __validate__(
    contract_address: ContractAddress, entry_point_selector: felt252, calldata: Array::<felt252>
) -> felt252 {
    starknet::VALIDATED
}
----

=== __execute__

如果 `__validate__` 函数验证成功， `__execute__` 函数将会被调用。它使用`starknet::call_contract_syscall` 将调用转发到目标合约。

[source,cairo]
----
#[external]
#[raw_output]
fn __execute__(
    contract_address: ContractAddress, entry_point_selector: felt252, calldata: Array::<felt252>
) -> Span::<felt252> {
    starknet::call_contract_syscall(
        address: contract_address,
        entry_point_selector: entry_point_selector,
        calldata: calldata.span()
    ).unwrap_syscall()
}
----

== 声明和部署“Hello World”账户合约

声明和部署过程与其他合约相同。在声明和部署“Hello World”账户合约之前，您必须先设置一个账户合约来管理部署过程。要了解有关部署账户合约的更多信息，请参阅本书第2章中有关部署的子章节。

记得使用 `scarb build` 进行编译（请参阅本书第2章中的Scarb子章节）。然后按照以下步骤声明和部署“Hello World”账户合约：

* 导出所需的环境变量：

[source,bash]
----
export STARKNET_NETWORK=alpha-goerli
export STARKNET_WALLET=starkware.starknet.wallets.open_zeppelin.OpenZeppelinAccount
----

* 声明合约（由于合约已经声明，您可以跳过此步骤。如果您仍想声明它，请运行以下命令，但您将收到错误提示）：

[source,bash]
----
starknet declare --contract target/release/starknetbook_chapter_7_HelloAccount.json --account my_account --max_fee 100000000000000000
----

对应类哈希是： 0x07e813097812d58afbb4fb015e683f2b84e4f008cbecc60fa6dece7734a2cdfe

* 部署合约

[source,bash]
----
starknet deploy --class_hash 0x07e813097812d58afbb4fb015e683f2b84e4f008cbecc60fa6dece7734a2cdfe --account my_account --max_fee 100000000000000000
----

完成这些步骤后，您将成功在Starknet上声明和部署了“Hello World”账户合约。https://testnet.starkscan.co/contract/0x01e6d7698ca76788c8f9c1091ec3d6d3f7167a9effe520402d832ca9894eba4a#overview[这里是已部署的版本]。

== 总结

在本小节中，我们使用“Hello World”示例深入探讨了Starknet中基本账户合约的细节。

我们还概述了在Starknet网络上声明和部署“Hello World”账户合约的步骤。部署过程涉及导出所需的环境变量、声明合约以及使用类哈希部署合约。

随着我们在探索Starknet账户合约方面的进展，下一个小节将介绍一个标准账户合约，将其与Open Zeppelin和Starkware定义的标准账户合约进行对比。这将进一步加强我们对账户合约在Starknet生态系统内部操作的理解。

[NOTE]
====
这本书是社区贡献出的成果，为社区而创建。

* 如果您学到了一些东西，或者没有收获，也请花点时间通过这个 https://a.sprig.com/WTRtdlh2VUlja09lfnNpZDo4MTQyYTlmMy03NzdkLTQ0NDEtOTBiZC01ZjAyNDU0ZDgxMzU=[三个问题的调查]提供反馈。
* 如果您发现任何错误或有其他建议，请毫不犹豫地在我们的 https://github.com/starknet-edu/starknetbook/issues[GitHub 存储库上开一个 issue]。
====

== **贡献力量**

> 释放你的热情，让《Starknet 之书》更加完美
> 
> 
> *《Starknet 之书》依然在不断完善中，而你的热情、专业知识和独到见解可以将它塑造成一部真正卓越的作品。不要害怕挑战现状或是颠覆这本书！齐心协力，我们一起创造这份宝贵的资源，造福无数人。*
> 
> *为公共事业贡献力量。如果你发现本书有改进的空间，那就抓住机会吧！查看我们的 https://github.com/starknet-edu/starknetbook/blob/main/CONTRIBUTING.adoc[指南] 并加入活力满满的社区。一起无畏共建 Starknet！*
> 

— Starknet 社区