[id="IntroToAA"]

= 账户抽象简介

_*免责声明：本部分引用了各方利益相关者的观点，本教程中任何错误或误解均由解释者承担责任。_

加密生态系统正处于一个关键的十字路口。作为领先平台之一，以太坊面临一个巨大的挑战：采用账户抽象（AA）或冒着“破坏加密货币所代表的本质——去中心化”的风险。

账户抽象对于以太坊来说是一项至关重要且具有改变游戏规则的创新。它是提高入门门槛、用户体验和安全性的关键（Martin Triay, Devcon 6）[1]。更重要的是，账户抽象是扩展自我保管的基石，这对于吸引下一个十亿用户（Julien Niset）[2]，（Motty Lavie）[7]非常重要。以太坊的未来，甚至整个加密货币领域的未来，取决于 账户抽象的成功。

此外，量子计算机对加密生态系统构成了严重的威胁，有可能破解传统的安全措施和签名。账户抽象可以帮助我们直面这一威胁，通过启用不同的签名方案，包括抗量子攻击的方案，来保护我们的资产。

如果没有账户抽象，以太坊将难以为用户提供无缝、安全和有力的体验，这可能导致用户大规模流失，涌向集中式交易所和钱包，这直接违背了支撑加密货币革命的去中心化原则。

中心化控制的危险已经司空见惯：审查、歧视和权力滥用的可能性。通过确保账户抽象成为以太坊发展的核心特征，我们保护了推动加密社区的核心价值观，并加强了去中心化经济的基础。

Starknet目前在协议层面在账户抽象的实施程度上处于领先地位，充当了账户抽象未来发展的“试验场”。在来自多个组织的许多杰出思想家的共同努力下，Starknet旨在彻底改变我们在加密领域中处理安全性、用户体验和自我保管的方式。


== 为什么账户抽象还没有被实现在以太坊（L1）层面呢？

那么，是什么阻碍了账户抽象在以太坊的L1层面实现呢？

主要问题在于删除外部拥有账户（EOA）。实现账户抽象需要对以太坊的核心协议进行重大改变。随着以太坊所保护的价值不断增长，实现账户抽象所需的协调变得越来越困难。

尽管账户抽象至关重要，但以太坊尚未支持它，因为其Ethereum虚拟机（EVM）存在限制。自以太坊早期以来就有账户抽象的提案，但它们一直被推迟，以便更紧急的提案得到优先考虑。

新的第二层（L2）虚拟机的开发专注于可扩展性，这使得账户抽象的实施取得了进展。例如，Starknet 和 ZKSync 都有原生的账户抽象，灵感来自EIP4337，这是一个被 Argent 的 Julien Niset 等专家认为是最好的提案。

许多账户抽象的支持者，如 Niset，似乎已经失去了 EOAs 将被消除，并且账户抽象将被实现在以太坊核心的希望。相反，他们现在正在推动通过类似 Starknet 的 L2 解决方案来广泛采用账户抽象。


== 参考资料：

* [1] Martin Triay, Devcon 6: https://www.youtube.com/watch?v=Osc_gwNW3Fw
* [2] Julien Niset: https://www.youtube.com/watch?v=OwppworJGzs
* [3] lightclient, Devcon 6: https://app.devcon.org/schedule/9mvqce
* [4] Starkware: https://medium.com/@starkware/how-starknet-is-revolutionizing-crypto-signing-ba3724077a79
* [5] Julien Niset, 2022: https://www.argent.xyz/blog/part-2-wtf-is-account-abstraction/
* [6] Yoav, Devcon 6: https://app.devcon.org/schedule/9mvqce
* [7] Motty Lavie, 2023: https://www.youtube.com/watch?v=FrxAdJYhSY8

其他文本：

* https://hackernoon.com/what-is-account-abstraction-and-why-is-everyone-talking-about-it
* https://ethereum.org/en/roadmap/account-abstraction/


[NOTE]
====
这本书是社区贡献出的成果，为社区而创建。

* 如果您学到了一些东西，或者没有收获，也请花点时间通过这个 https://a.sprig.com/WTRtdlh2VUlja09lfnNpZDo4MTQyYTlmMy03NzdkLTQ0NDEtOTBiZC01ZjAyNDU0ZDgxMzU=[三个问题的调查]提供反馈。
* 如果您发现任何错误或有其他建议，请毫不犹豫地在我们的 https://github.com/starknet-edu/starknetbook/issues[GitHub 存储库上开一个 issue]。
====
