[id="multicall"]

= 多重调用

====
贡献：这个子章节缺少一个声明、部署和与合约交互的示例。我们很希望看到您的贡献！请提交PR。
====

https://github.com/joshstevens19/ethereum-multicall#readme[多重调用] 是一种强大的技术，允许将多个常量智能合约函数调用聚合到单个调用中，从而产生一个合并的输出。使用 Starknet 的账户抽象功能，可以将多个调用无缝地集成到账户合约中。

== 为什么使用多重调用？

多个调用在几种情况下非常方便。以下是一些示例：

1. *去中心化交易所的代币交换*：在去中心化交易所（DEX）上进行典型的代币交换操作时，您首先需要批准代币的支出，然后再启动交换。从用户体验的角度来看，执行这些操作可能很麻烦。使用多个调用，这些调用可以合并为单个事务，简化用户的任务。
2. *获取区块链数据*：当您想从区块链查询两个不同代币的价格时，为了保持一致性，最好从同一个块中获取这些价格。多重调用可以返回最新的块高和已经聚合的结果，实现这种一致性。

在账户抽象的背景下，多重调用交易的好处将可以被最大化。

== 合约账户中的多重调用功能

为了实现多重调用，我们可以在账户合约中引入特定的函数。以下是两个核心函数：

=== `_execute_calls` 函数

`_execute_calls` 函数负责执行多重调用。它遍历调用数组，执行它们并汇总结果。

[Source,Rust]
----
fn _execute_calls(mut calls: Array<AccountCall>, mut res:Array::<Array::<felt>>) -> Array::<Array::<felt>> {
    match calls.pop_front() {
        Option::Some(call) => {
            let _res = _call_contract(call);
            res.append(_res);
            return _execute_calls(calls, res);
        },
        Option::None(_) => {
            return res;
        },
    }
}
----

除了传统的 *"_ _execute_ _"* 函数之外，将 *"_execute_calls"* 函数添加到您的账户合约中可以确保您可以使用合约账户进行多个调用。

上面的代码是一个简单的示例片段，其中 *"return _execute_calls(calls, res);"* 语句会对 *"_execute_calls_"* 函数进行递归调用，从而将调用绑定在一起。最终的结果将汇总并返回在 *_res_* 变量中。

=== `_call_contract` 函数

`_call_contract` 函数是一个辅助函数，用于进行单个合约调用。

[,Rust]
----
fn _call_contract(call: AccountCall) -> Array::<felt> {
    starknet::call_contract_syscall(
        call.to, call.selector, call.calldata
    ).unwrap_syscall()
}
----

== 注意事项

虽然多重调用在用户体验和数据一致性方面提供了显著的优点，但需要注意的是，与单个调用相比，它可能并不会显著降低 gas 费用。然而，使用多重调用的主要优势在于它确保结果来自同一区块，从而提供了更好的用户体验。

[NOTE]
====
这本书是社区贡献出的成果，为社区而创建。

* 如果您学到了一些东西，或者没有收获，也请花点时间通过这个 https://a.sprig.com/WTRtdlh2VUlja09lfnNpZDo4MTQyYTlmMy03NzdkLTQ0NDEtOTBiZC01ZjAyNDU0ZDgxMzU=[三个问题的调查]提供反馈。
* 如果您发现任何错误或有其他建议，请毫不犹豫地在我们的 https://github.com/starknet-edu/starknetbook/issues[GitHub 存储库上开一个 issue]。
====

== **贡献力量**

> 释放你的热情，让《Starknet 之书》更加完美
> 
> 
> *《Starknet 之书》依然在不断完善中，而你的热情、专业知识和独到见解可以将它塑造成一部真正卓越的作品。不要害怕挑战现状或是颠覆这本书！齐心协力，我们一起创造这份宝贵的资源，造福无数人。*
> 
> *为公共事业贡献力量。如果你发现本书有改进的空间，那就抓住机会吧！查看我们的 https://github.com/starknet-edu/starknetbook/blob/main/CONTRIBUTING.adoc[指南] 并加入活力满满的社区。一起无畏共建 Starknet！*
> 

— Starknet 社区
