[id="starknet_aa"]

= 探索Starknet的账户抽象模型

现在我们更好地了解了“账户抽象”（AA）的概念，让我们在 Starknet中 实际编写它。

== 账户合约接口

虽然账户合约本质上只是智能合约，但它们具有使它们与其他智能合约区别开来的方法。下面是一个实现账户抽象协议的账户合约接口。它与一个公钥相关联，可以验证和执行交易。它的作用如下：

* `constructor`： 这个可选的方法初始化账户合约。尽管账户合约可以在没有构造函数的情况下存在，但在构造函数中建立相关的公钥是一种常见的做法。
* `validate_transaction`： 一个可选的辅助方法， `validate_transaction`检查交易的有效性。这可能涉及将签名与相关的公钥进行比较，或者是合约创建者定义的任何其他验证方法。
* `__validate_deploy__`： 这个方法在部署过程中被调用，用于验证新合约的部署。
* `__validate_declare__`： 这个方法验证新合约的声明。它确认合约声明的语法和语义是正确的。
* `__validate__`： 这个方法在交易执行之前验证交易。它确保交易遵守合约中定义的规则。
* `__execute__`： 在交易被验证之后， `__execute__` 是执行一系列合约调用的方法。

账户合约通过只允许执行具有有效签名的交易，在确保 Starknet 网络安全方面发挥着至关重要的作用。

以下是一个通用的账户合约实现：

[,Rust]
----
#[account_contract]
mod Account {
    use starknet::ContractAddress;

    #[constructor]
    fn constructor(public_key_: felt252);

    fn isValidSignature() -> felt252;

    #[external]
    fn __validate_deploy__(
        class_hash: felt252, contract_address_salt: felt252, public_key_: felt252
    ) -> felt252;

    #[external]
    fn __validate_declare__(class_hash: felt252) -> felt252;

    #[external]
    fn __validate__(
        contract_address: ContractAddress, entry_point_selector: felt252, calldata: Array<felt252>
    ) -> felt252;

    #[external]
    #[raw_output]
    fn __execute__(mut calls: Array<Call>) -> Span<felt252>;
}
----

账户合约的入口点是其可调用函数。让我们详细探讨一下这些函数：

* `constructor`： 这个函数不是必须的，但对于设置账户合约非常有用。它接受一个 `public_key` 参数，表示与账户相关联的公钥。在未来，可能会有一个 `setPublicKey()` 函数来方便账户转移。
* `isValidSignature`： 受 EIP-1271 启发，该函数如果给定的签名有效，则返回 true；否则，它会回滚。
* `__validate__`： 允许您定义任意逻辑来确定交易是否有效。它允许您为确定交易的有效性定义自定义逻辑。它不能读取其他合约的存储，这有助于防止垃圾邮件。当账户合约接收到交易时，它会调用 `__validate__` 函数。该函数接受以下参数（calldata）：
 ** `contract_address: ContractAddress`： 目标合约地址。
 ** `entry_point_selector: felt252`： 要在目标合约上调用的函数。
 ** `calldata: Array<felt252>`： 表示函数参数的数组。请记住，calldata 是用于调用函数的参数。
* `__validate_declare__`： 该函数在声明新合约之前验证签名。它接受一个单一的参数 `class_hash`，表示要声明的合约的类哈希。
* `__execute__`： 该函数作为所有用户与任何合约交互的状态更改入口点，包括管理账户合约本身。在 `__validate__`成功验证后调用它。该函数接受一个参数 `mut calls`，它是一个 `Call` 结构体的数组。

== Call 结构体

`Call` 结构体表示对合约的单个调用：

[,Rust]
----
struct Call {
    to: ContractAddress,
    selector: felt252,
    calldata: Array<felt252>
}
----

它包含以下字段：

* `to`： 目标合约地址。
* `selector`： 要在目标合约上调用的函数的选择器。
* `calldata`： 表示函数参数的数组。

== 总结

在本章中，我们探讨了 Starknet 中的账户抽象模型，重点关注了账户合约及其方法。

进一步总结：

* 账户合约是实现账户抽象协议的智能合约。
* 它们提供了验证和执行交易和合约部署的方法。
* 它们通过允许用户定义自定义验证逻辑来提供灵活性。

在下一小节中，我们将实现一个简单的账户合约，并学习如何在Starknet上部署它。这将提供一个实际的理解，了解账户合约的工作原理以及如何与它们交互。


[NOTE]
====
这本书是社区贡献出的成果，为社区而创建。

* 如果您学到了一些东西，或者没有收获，也请花点时间通过这个 https://a.sprig.com/WTRtdlh2VUlja09lfnNpZDo4MTQyYTlmMy03NzdkLTQ0NDEtOTBiZC01ZjAyNDU0ZDgxMzU=[三个问题的调查]提供反馈。
* 如果您发现任何错误或有其他建议，请毫不犹豫地在我们的 https://github.com/starknet-edu/starknetbook/issues[GitHub 存储库上开一个 issue]。
====