[id="why_aa"]

= 为什么需要账户抽象？

== 钱包和用户
加密钱包是引导用户进入 web3 的重要组成部分。然而，钱包可能会让人感到不知所措，难以使用，因为一个小错误可能会导致大量资产损失。

让我们来看看今天钱包存在的一些问题：
* 大多数以太坊用户使用集中式交易所，因为管理自我保管钱包很难；这并不是真正的自我保管。 +
* 五年后，通过将 12 个单词写在纸上来保护我们的资产将会变得很奇怪。种子短语应该是过去的事情。 +
* 对于使用自我保管钱包的用户来说，没有安全保障。 +

让我们快速了解一下当前以太坊上的账户如何工作。

== 以太坊上的账户

在以太坊上有两种类型的账户：

* *外部拥有账户* （EOA） +
* *合约账户* （CA）.

在接下来的文章中，我们将把 EOAs 称为账户，因为它们与本章最相关。

正如名称所示，EOAs 是由区块链外部的某个实体（即用户）拥有的账户。在以太坊上，账户的状态只能通过交易进行修改，这些交易必须由 EOA 发起（在触发链中可能还有合约账户）。

*这是否意味着任何人都可以从任何EOA触发交易？* 不是的，这就是签名者的概念介入的地方。

在以太坊上，每个账户都与一个称为签名者的加密对象相关联。签名者，也称为密钥对，由两个密钥组成：私钥和公钥。

私钥，也称为秘密密钥，可用于签署数字消息，而公钥可以使任何人验证特定签名是由其对应的私钥签署的。

*账户如何与签名者相关联？* 通过账户地址。

EOA 的地址是从签名者的公钥派生的。更具体地说，地址是公钥的 Keccak-256 哈希的最后 20 个字节。

因此，账户的所有者可以通过使用相应的私钥签署交易的参数来授权从其账户发起交易。

*但如果您丢失了私钥怎么办？*

因为您的私钥就是您的账户，所以丢失了私钥就意味着丢失了账户。

更糟糕的是，如果别人拥有了您的私钥，他们也就拥有了您的账户……以及其中包含的所有代币。而且您无能为力！由于私钥的丢失或盗窃，已经有数亿美元的资产已经丢失或被盗。

这就是 *账户抽象* 可以帮助用户的地方——通过社交恢复和其他一些很酷的功能，账户抽象可能是解锁加密货币大规模采用的关键。

让我们在下一章节中深入了解它。

[NOTE]
====
这本书是社区贡献出的成果，为社区而创建。

* 如果您学到了一些东西，或者没有收获，也请花点时间通过这个 https://a.sprig.com/WTRtdlh2VUlja09lfnNpZDo4MTQyYTlmMy03NzdkLTQ0NDEtOTBiZC01ZjAyNDU0ZDgxMzU=[三个问题的调查]提供反馈。
* 如果您发现任何错误或有其他建议，请毫不犹豫地在我们的 https://github.com/starknet-edu/starknetbook/issues[GitHub 存储库上开一个 issue]。
====

== **贡献力量**

> 释放你的热情，让《Starknet 之书》更加完美
> 
> 
> *《Starknet 之书》依然在不断完善中，而你的热情、专业知识和独到见解可以将它塑造成一部真正卓越的作品。不要害怕挑战现状或是颠覆这本书！齐心协力，我们一起创造这份宝贵的资源，造福无数人。*
> 
> *为公共事业贡献力量。如果你发现本书有改进的空间，那就抓住机会吧！查看我们的 https://github.com/starknet-edu/starknetbook/blob/main/CONTRIBUTING.adoc[指南] 并加入活力满满的社区。一起无畏共建 Starknet！*
> 

— Starknet 社区
