[id="memory"]

= 内存模型

== 连续性
程序访问的内存地址必须是连续的。
例如，如果访问了地址 7 和 9，那么在程序结束前，必须也访问 8。
证明者将会自动用任意值填充空的内存单元。
有这样的空隙是低效的，因为这意味着内存正在被消耗却没有被使用。
引入过多的空洞可能使生成证明过于昂贵。
然而，这仍然不违反可靠性保证——无论如何都不能生成假的证明。
在实践中，我们可以在内存单元中存储值，同时跳过内存单元（参见 [registers/cairo/ap_fp_example.cairo](https://github.com/starknet-edu/starknetbook/blob/main/chapters/modules/chapter_5/pages/registers/cairo/ap_fp_example.cairo)），证明者将填充空的单元以保持内存的连续性。

== 只写一次，只读
我们可以把 Cairo 的内存想象为只能写一次的内存（只能被写入一次）。
如果我们赋值 `assert [d] = 7;`，那么在我们的程序执行结束前，内存中的地址 `d` 将始终包含值 `7`。
我们无法在运行时更改地址 `d` 存储的内容，我们只能写入一次，然后读取它。

== 相对地址
每个内存单元的绝对地址只能在 Cairo 程序执行结束时确定。
也就是说，我们正在处理相对于其他地址的地址。
我不能说我想要找到等同于 `“I rule here”` 的 felt 在内存单元 32 中。
我可以说，例如，我希望找到等同于 `Cairo rule”` 的 felt 在下一个空单元中，或者在当前使用的单元的三个单元中。
你注意到我们在讨论的不是绝对地址，而是相对地址了吗？
我们将在下一节中回顾寄存器，这对此非常有用。

[附注]
====
《Starknet 之书》是 Starknet 社区成员合力之作，便于社区成员学习之用。

* 无论你是否有所收获，烦请填写此问卷， https://a.sprig.com/WTRtdlh2VUlja09lfnNpZDo4MTQyYTlmMy03NzdkLTQ0NDEtOTBiZC01ZjAyNDU0ZDgxMzU=[简单回答三个问题] ，给予我们反馈。
* 若发现任何错误，或有其他建议，请在我们的 https://github.com/starknet-edu/starknetbook/issues[Github 仓库]发起问题单 (Issues)。
====



== 贡献力量

[quote, Starknet 社区]

____

释放你的热情，让《Starknet 之书》更加完美

《Starknet 之书》依然在不断完善中，而你的热情、专业知识和独到见解可以将它塑造成一部真正卓越的作品。不要害怕挑战现状或是颠覆这本书！齐心协力，我们一起创造这份宝贵的资源，造福无数人。

为公共事业贡献力量。如果你发现本书有改进的空间，那就抓住机会吧！查看我们的https://github.com/starknet-edu/starknetbook/blob/main/CONTRIBUTING.adoc[指南]并加入活力满满的社区。一起无畏共建 Starknet！

____