[id="risc"]

= Cairo 指令集（代数 RISC）

这是一个由 https://twitter.com/liamzebedee/status/1516298353080152064[@liamzebedee] 创造的用于理解 Cairo 的精巧的思维模型：

* AIR = STARK 的汇编
* Cairo 语言 = STARK 的 Java

Java 代码转换为 JVM 字节码，再解析为汇编；
同样，Cairo（语言）代码被解析为 CairoVM 字节码，再解析为 AIR。
JVM 在 x86 处理器上执行（例如 java.exe），而 CairoVM 在 STARK 证明器上执行。
STARK 证明器最终将嵌入硬件，就像其他加密协处理器（TPM，安全环）一样。

不同于在由晶体管构成的物理芯片上执行的普通指令集，Cairo 在 AIR 上执行（执行轨迹使用 AIR 验证）。
粗略地说，设计 AIR（因此，设计一个将由 AIR 执行的指令集）时最重要的约束是最小化使用的轨迹单元数。

指令集是 Cairo CPU 在一个步骤中可以执行的操作集合。
Cairo 使用一个小而简单，但相对有表现力的指令集；
它被选定是为了使得对应的 AIR 尽可能高效。
它是平衡：
. 需要非常少轨迹单元的简单指令的最小集合；
和
. 能够减少所需步骤的足够强大的指令。

特别地：

. 支持加法和乘法。
. 支持检查两个值是否相等，但没有检查某个值是否小于另一个值的指令（这样的指令将需要更多轨迹单元，因为有限域不支持元素的代数友好线性排序）。


这种极简的指令集被称为代数 RISC（Reduced Instruction Set Computer）；
"代数" 指的是支持的操作是域操作。
使用代数 RISC 让我们可以构建一个每步只有 51 个轨迹单元的 Cairo 的 AIR。

[附注]
====
《Starknet 之书》是 Starknet 社区成员合力之作，便于社区成员学习之用。

* 无论你是否有所收获，烦请填写此问卷， https://a.sprig.com/WTRtdlh2VUlja09lfnNpZDo4MTQyYTlmMy03NzdkLTQ0NDEtOTBiZC01ZjAyNDU0ZDgxMzU=[简单回答三个问题] ，给予我们反馈。
* 若发现任何错误，或有其他建议，请在我们的 https://github.com/starknet-edu/starknetbook/issues[Github 仓库]发起问题单 (Issues)。
====



== 贡献力量

[quote, Starknet 社区]

____

释放你的热情，让《Starknet 之书》更加完美

《Starknet 之书》依然在不断完善中，而你的热情、专业知识和独到见解可以将它塑造成一部真正卓越的作品。不要害怕挑战现状或是颠覆这本书！齐心协力，我们一起创造这份宝贵的资源，造福无数人。

为公共事业贡献力量。如果你发现本书有改进的空间，那就抓住机会吧！查看我们的https://github.com/starknet-edu/starknetbook/blob/main/CONTRIBUTING.adoc[指南]并加入活力满满的社区。一起无畏共建 Starknet！

____