[id="segments"]

= 段

在 Cairo 中访问内存时，我们使用段。这些段是内存区域。
然后将这些段连接起来，创建一个段的列表：我们的内存。
正如我们之前提到的，Cairo 中的地址是相对的：它们不仅相对于彼此，还相对于它们所属的段。
因此，Cairo 中的一个地址是这样表示的：`<段>:<偏移>`。
其中 `<段>` 是段号（我们在编写程序时不知道它，它在运行我们的程序时被分配）；
`<偏移>` 是地址相对于段的位置。
这种表示地址的方式称为 "可重定位的"：最后，当我们运行我们的程序时，这些内存单元将被重新定位，使得内存最终连续。

任何 Cairo 程序都需要的两个段是：

* *段 0* - 程序段。
Cairo 程序本身存储在程序段中。
这个段的长度是固定的，包含了 Cairo 程序的数值表示。
寄存器 `pc` 在这里开始。
* *段 1* - 执行段。
这是寄存器 `ap` 和 `fp` 开始的地方，以及在运行 Cairo 程序期间生成的数据（变量，函数调用的返回地址等）存储的地方。
执行段的长度是可变的，因为它取决于，例如，程序输入。

如我们之前看到的，我们可以使用具有自己内存段的 builtins。
编译 [builtins/cairo/hash.cairo](https://github.com/starknet-edu/starknetbook/blob/main/chapters/modules/chapter_5/pages/builtins/cairo/hash.cairo) （`cairo-compile builtins/cairo/hash.cairo --output hash_compiled.json`）并使用 `--print-memory` 标志运行它（`cairo-run --program hash_compiled.json --print_output --layout=small --print_memory`）。
注意我们在其中有值。
[附注]
====
《Starknet 之书》是 Starknet 社区成员合力之作，便于社区成员学习之用。

* 无论你是否有所收获，烦请填写此问卷， https://a.sprig.com/WTRtdlh2VUlja09lfnNpZDo4MTQyYTlmMy03NzdkLTQ0NDEtOTBiZC01ZjAyNDU0ZDgxMzU=[简单回答三个问题] ，给予我们反馈。
* 若发现任何错误，或有其他建议，请在我们的 https://github.com/starknet-edu/starknetbook/issues[Github 仓库]发起问题单 (Issues)。
====



== 贡献力量

[quote, Starknet 社区]

____

释放你的热情，让《Starknet 之书》更加完美

《Starknet 之书》依然在不断完善中，而你的热情、专业知识和独到见解可以将它塑造成一部真正卓越的作品。不要害怕挑战现状或是颠覆这本书！齐心协力，我们一起创造这份宝贵的资源，造福无数人。

为公共事业贡献力量。如果你发现本书有改进的空间，那就抓住机会吧！查看我们的https://github.com/starknet-edu/starknetbook/blob/main/CONTRIBUTING.adoc[指南]并加入活力满满的社区。一起无畏共建 Starknet！

____