_版权所有 © 2019 Starkware Industries Ltd。根据 Apache 许可证版本 2.0（“许可证”）许可。除非符合许可证的规定，否则您不得使用此文件。您可以在
https://www.starkware.co/open-source-license/ 获取许可证的副本。除非适用法律要求或书面同意，否则根据许可证分发的软件是基于“按原样”分发的，没有任何形式的明示或暗示的保证或条件。请参阅许可证以了解许可权限和限制的具体语言。_

== Part 1: 轨迹和低次扩展

* https://www.youtube.com/watch?v=Y0uJz9VL3Fo[视频讲解 (youtube)]
* https://starkware.co/wp-content/uploads/2021/12/STARK101-Part1.pdf[幻灯片
(PDF)]

今天我们将为有限域上的 FibonacciSq 序列开发一个 STARK 证明程序。FibonacciSq 序列由递推关系 latexmath:[a_{n+2} = a_{n+1} ^2 + a_n ^2] 定义。到最后的时候，您的代码将产生一个 _STARK_ 证明，证明以下
陈述：*我知道一个域元素 latexmath:[X\in \mathbb{F}]，由此，以 latexmath:[1, X] 开始的 FibonacciSq 序列的第1023个元素是 latexmath:[2338775057]*。

=== 基本原则

==== FieldElement class

我们使用 `+FieldElement+` 类来表示有限域上的元素。您可以使用整数构造 `+FieldElement+` 的实例，然后进行加法、乘法、除法、求逆等运算。这个类的底层域是 latexmath:[\mathbb{F}_{3221225473}]
(latexmath:[3221225473 = 3 \cdot 2^{30} + 1])，所以所有的运算都是在模 3221225473 意义下进行的。您可以通过运行以下单元格 (shift
enter) 来尝试。

[source,python]
----
从域导入 FieldElement
FieldElement(3221225472) + FieldElement(10)
----

== FibonacciSq Trace

首先，让我们构造一个长度为 1023 的列表 `+a+` ，其中前两个元素将分别表示为 1 和 3141592 的 FieldElement 对象。接下来的 1021 个元素将是由这两个元素所诱导的 FibonacciSq 序列。 `+a+` 被称为 FibonacciSq 的轨迹，或者在上下文清晰的情况下，简称为轨迹。我们按照以下方式计算 `+a+` ：

[source,python]
----
a = [FieldElement(1), FieldElement(3141592)]
while len(a) < 1023:
    a.append(a[-2] * a[-2] + a[-1] * a[-1])
----

== 测试你的代码

运行下一个单元格以测试您是否正确地填充了 `+a+`。请注意，这实际上是一个验证器，尽管它非常简单和冗长，因为它逐个元素地遍历序列，确保它是正确的。

[source,python]
----
assert len(a) == 1023, 'The trace must consist of exactly 1023 elements.'
assert a[0] == FieldElement(1), 'The first element in the trace must be the unit element.'
for i in range(2, 1023):
    assert a[i] == a[i - 1] * a[i - 1] + a[i - 2] * a[i - 2], f'The FibonacciSq recursion rule does not apply for index {i}'
assert a[1022] == FieldElement(2338775057), 'Wrong last element!'
print('Success!')
----

== 多项式的思考

现在，我们希望将这个序列视为某个未知多项式 latexmath:[f] 的 1022 阶评估结果（由于 Unisolvence 定理）。我们将选择域为某个大小为 1024 的子群 latexmath:[G \subseteq \mathbb{F}^\times]，原因稍后会变得清晰。

(回想一下，latexmath:[\mathbb{F}^\times] 表示从域 latexmath:[\mathbb{F}]中删除零元素后的乘法群。大小为 1024 的子群是存在的，因为 latexmath:[\mathbb{F}^\times] 是大小为 latexmath:[3\cdot 2^{30}]的循环群，因此它包含大小为 latexmath:[2^i] 的子群，其中 latexmath:[0 \leq i \leq 30])。

=== 找到一个大小为 1024 的群

如果我们找到一个元素 latexmath:[g \in \mathbb{F}]，其（乘法）阶为1024，则 latexmath:[g] 将生成这样的群。类 `+FieldElement+` 提供了一个静态方法 `+generator()+` 该方法返回生成 latexmath:[\mathbb{F}^\times] （其阶为 latexmath:[|\mathbb{F}^\times|]） 的元素。

. 使用它来获得生成器 latexmath:[g] 用于 latexmath:[G]。
. 创建一个名为  `+G+` 的列表，其中包含 latexmath:[G] 的所有元素，使得 latexmath:[G[i] := g^i]。

_提示：当 latexmath:[k] 除以 latexmath:[|\mathbb{F}^\times|]时，latexmath:[g^k] 生成一个大小为 latexmath:[\frac {|\mathbb{F}^\times|}{k}] 的群，某些 `+FieldElement+` latexmath:[x] 的 n次方可以通过调用 `+x ** n+` 来计算。_

解决方案：

[source,python]
----
g = FieldElement.generator() ** (3 * 2 ** 20)
G = [g ** i for i in range(1024)]
----

运行下一个单元格来测试你的代码。

[source,python]
----
# Checks that g and G are correct.
assert g.is_order(1024), 'The generator g is of wrong order.'
b = FieldElement(1)
for i in range(1023):
    assert b == G[i], 'The i-th place in G is not equal to the i-th power of g.'
    b = b * g
    assert b != FieldElement(1), f'g is of order {i + 1}'
    
if b * g == FieldElement(1):
    print('Success!')
else:
    print('g is of order > 1024')
----

== 多项式类

我们为您提供了一个名为 `+Polynomial+` 的类。构造一个 `+Polynomial+` 最简单的方法是使用变量 `+X+` (注意它是大写字母 `+X+`) ，它代表变量 latexmath:[x]:

[source,python]
----
from polynomial import X
# The polynomial 2x^2 + 1.
p = 2*X**2 + 1
# Evaluate p at 2:
print(p(2))
----

== 插值多项式

我们的 `+polynomial+` 模块提供了一个拉格朗日插值函数，其参数为：

* x_values:G 的 x_values，其多项式的值是已知的。[列表]
* y_values: 相关的 y-values。[列表]

此函数返回次数小于 < `+len(x_values)+` 的唯一 `+多项式+`，该多项式对于所有 i，其在 `+x_values[i]+` 处的取值为 `+y_values[i]+`。

运行以下单元格以获取有关函数 `+interpolate_poly+` 的帮助。

[source,python]
----
from polynomial import interpolate_poly
interpolate_poly?
----

假设 `+a+` 包含某个多项式在 `+G+` 上的值（除了  `+G[-1]+`，因为 `+a+` 比 `+G[-1]+` 短一个元素）。使用 `+interpolate_poly()+` 获取 `+f+`，并获取其在 `+FieldElement(2)+` 处的值。

解决方案：

[source,python]
----
f = interpolate_poly(G[:-1], a)
v = f(2)
----

运行测试：

[source,python]
----
assert v == FieldElement(1302089273)
print('Success!')
----

== 在更大的域进行评估

将迹视为多项式 latexmath:[f] 在 latexmath:[G] 上的取值，现在可以通过在更大的域上评估 latexmath:[f] 来扩展它，从而创建一个 Reed-Solomon 纠错码。

=== 陪集

为此，我们必须决定一个更大的域，用于评估 latexmath:[f]。 我们将使用一个比 latexmath:[G] 大8倍的域。这样一个域的自然选择是选择一个大小为 8192 的群 latexmath:[H] (因为 8192 可以整除 latexmath:[|\mathbb{F}^\times|])，并将它位移到 latexmath:[\mathbb{F}^\times] 的生成元处，从而获得一个 latexmath:[H] 的 https://en.wikipedia.org/wiki/Coset[陪集] 。

创建一个名为 `+H+` 的列表，其中包含 latexmath:[H] 的元素，并将它们乘以 latexmath:[\mathbb{F}^\times] 的生成元，从而获得一个名为 `+eval_domain+` 的列表。换句话说，对于 latexmath:[h] 是 latexmath:[H] 的生成元， latexmath:[w] 是 latexmath:[\mathbb{F}^\times] 的生成元，eval_domain = latexmath:[{w\cdot h^i | 0 \leq i <8192 }]。

提示：您已经知道如何获得 latexmath:[H]，方法与几分钟前获得 latexmath:[G] 的方法类似。

解决方案：

[source,python]
----
w = FieldElement.generator()
h = w ** ((2 ** 30 * 3) // 8192)
H = [h ** i for i in range(8192)]
eval_domain = [w * x for x in H]
----

运行测试：

[source,python]
----
from hashlib import sha256
assert len(set(eval_domain)) == len(eval_domain)
w = FieldElement.generator()
w_inv = w.inverse()
assert '55fe9505f35b6d77660537f6541d441ec1bd919d03901210384c6aa1da2682ce' == sha256(str(H[1]).encode()).hexdigest(),\
    'H list is incorrect. H[1] should be h (i.e., the generator of H).'
for i in range(8192):
    assert ((w_inv * eval_domain[1]) ** i) * w == eval_domain[i]
print('Success!')
----

== 在陪集上进行评估

现在是时候使用 `+interpolate_poly+` 和 `+Polynomial.poly+` 在陪集上进行评估了。请注意，它在我们的Python模块中实现得相当简单，因此插值可能需要长达一分钟的时间。即使使用更高效的方法（如 FFT），插值和评估迹多项式仍是 STARK协议中计算密集度最高的步骤之一。

解决方案：

[source,python]
----
f = interpolate_poly(G[:-1], a)
f_eval = [f(d) for d in eval_domain]
----

运行测试：

[source,python]
----
# Test against a precomputed hash.
from hashlib import sha256
from channel import serialize
assert '1d357f674c27194715d1440f6a166e30855550cb8cb8efeb72827f6a1bf9b5bb' == sha256(serialize(f_eval).encode()).hexdigest()
print('Success!')
----

== 承诺

我们将使用基于 https://en.wikipedia.org/wiki/SHA-2[Sha256] 的
https://en.wikipedia.org/wiki/Merkle_tree[Merkle Trees] 作为我们的承诺方案。您可以在 `+MerkleTree+` 类找到它的一个简单实现。运行下一个单元格 （为了本教程的目的，这也是对整个计算正确性的测试）：

[source,python]
----
from merkle import MerkleTree
f_merkle = MerkleTree(f_eval)
assert f_merkle.root == '6c266a104eeaceae93c14ad799ce595ec8c2764359d7ad1b4b7c57a4da52be04'
print('Success!')
----

== 通道

理论上，STARK证明系统是一个介于两个参与方之间的交互协议 - 证明器和验证者。 实际上，我们使用
https://en.wikipedia.org/wiki/Fiat%E2%80%93Shamir_heuristic[Fiat-Shamir 启发式算法] 将这个交互协议转换为非交互式证明。在本教程中，您将使用实现此转换的 `+Channel+` 类。这个通道在某种意义上取代了验证者的角色， 因为证明器（即您编写的程序）将发送数据，并接收随机数或随机的 `+FieldElement+` 的实例。

这段简单的代码实例化了一个通道对象，并将您的 Merkle Tree 根节点发送给它。稍后，可以调用通道对象以提供随机数或随机场元素。

[source,python]
----
from channel import Channel
channel = Channel()
channel.send(f_merkle.root)
----

最后，您可以通过打印成员变量 `+Channel.proof+` 来检索到目前为止的证明（即，在某个点之前通过通道传递的所有内容）。

[source,python]
----
print(channel.proof)
----
